### ISSUE TITLE
File Formats

### ISSUE THREAD

**Issue by ETalanian** [m0bilebtw/c-engineer-completed#14]
Hey there,  I replaced several of the sound files and I'm having trouble getting them to work.

Those that I downloaded as .wav files seem to work perfectly, but the files I downloaded as .mp3 don't.  I see in the readme that this is working as intended, but I tried loading the mp3 files into Audacity and exporting as .wav files, and they still aren't working!  Is there any way to convert mp3s to wavs and have the plugin be able to play them, or am I out of luck if I can't find the sound I want in .wav format to download?

**Comment by m0bilebtw** [comment]
The ones you converted from MP3 to wav yourself, do they play fine in standalone audio players?

**Comment by ETalanian** [comment]
Yes, I originally tested with VLC Media Player and I've confirmed they also play fine in Windows Media Player.

I've zipped and added the death sound I downloaded as an mp3 then exported as wav:
[death sound.zip](https://github.com/m0bilebtw/c-engineer-completed/files/9305105/death.sound.zip)

**Comment by m0bilebtw** [comment]
Odd - are there any clues in the client logs?

**Comment by ETalanian** [comment]
`2022-08-13 08:30:57 [Client] WARN  com.github.m0bilebtw.SoundEngine - Failed to load C Engineer sound DEATH
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 32 bit, stereo, 8 bytes/frame, little-endian not supported.
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(Unknown Source)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(Unknown Source)
	at java.desktop/com.sun.media.sound.AbstractDataLine.open(Unknown Source)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(Unknown Source)
	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectClip.open(Unknown Source)
	at com.github.m0bilebtw.SoundEngine.loadClip(SoundEngine.java:27)
	at com.github.m0bilebtw.SoundEngine.playClip(SoundEngine.java:52)
	at com.github.m0bilebtw.CEngineerCompletedPlugin.onActorDeath(CEngineerCompletedPlugin.java:193)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:179)
	at cs.ss(cs.java:64036)
	at cs.bu(cs.java)
	at lv.z(lv.java:605)
	at fi.q(fi.java:74)
	at client.ht(client.java:6724)
	at client.fd(client.java:3088)
	at client.aj(client.java:1069)
	at as.dh(as.java:359)
	at as.run(as.java:338)
	at java.base/java.lang.Thread.run(Unknown Source)`

Is it because of the encoding option I chose in Audacity when exporting as a .wav?

https://i.imgur.com/YIh8UoX.png

**Comment by m0bilebtw** [comment]
It certainly could be, is there a 16 or 24 bit option?

**Comment by ETalanian** [comment]
16-bit option worked, thank you!!
